var heroes = {
  npc_dota_hero_abaddon: { "image": "0.png"},
  npc_dota_hero_abyssal_underlord: { "image": "1.png"},
  npc_dota_hero_alchemist: { "image": "2.png"},
  npc_dota_hero_ancient_apparition: { "image": "3.png"},
  npc_dota_hero_antimage: { "image": "4.png"},
  npc_dota_hero_arcwarden: { "image": "5.png"},
  npc_dota_hero_axe: { "image": "6.png"},
  npc_dota_hero_bane: { "image": "7.png"},
  npc_dota_hero_batrider: { "image": "8.png"},
  npc_dota_hero_beastmaster: { "image": "9.png"},
  npc_dota_hero_bloodseeker: { "image": "10.png"},
  npc_dota_hero_bounty_hunter: { "image": "11.png"},
  npc_dota_hero_brewmaster: { "image": "12.png"},
  npc_dota_hero_bristleback: { "image": "13.png"},
  npc_dota_hero_broodmother: { "image": "14.png"},
  npc_dota_hero_centaur: { "image": "15.png"},
  npc_dota_hero_chaos_knight: { "image": "16.png"},
  npc_dota_hero_chen: { "image": "17.png"},
  npc_dota_hero_clinkz: { "image": "18.png"},
  npc_dota_hero_crystal_maiden: { "image": "19.png"},
  npc_dota_hero_dark_seer: { "image": "20.png"},
  npc_dota_hero_dazzle: { "image": "21.png"},
  npc_dota_hero_death_prophet: { "image": "22.png"},
  npc_dota_hero_disruptor: { "image": "23.png"},
  npc_dota_hero_doom_bringer: { "image": "24.png"},
  npc_dota_hero_dragon_knight: { "image": "25.png"},
  npc_dota_hero_drow_ranger: { "image": "26.png"},
  npc_dota_hero_earth_spirit: { "image": "27.png"},
  npc_dota_hero_earthshaker: { "image": "28.png"},
  npc_dota_hero_elder_titan: { "image": "29.png"},
  npc_dota_hero_ember_spirit: { "image": "30.png"},
  npc_dota_hero_enchantress: { "image": "31.png"},
  npc_dota_hero_enigma: { "image": "32.png"},
  npc_dota_hero_faceless_void: { "image": "33.png"},
  npc_dota_hero_furion: { "image": "34.png"},
  npc_dota_hero_gyrocopter: { "image": "35.png"},
  npc_dota_hero_huskar: { "image": "36.png"},
  npc_dota_hero_invoker: { "image": "37.png"},
  npc_dota_hero_jakiro: { "image": "38.png"},
  npc_dota_hero_juggernaut: { "image": "39.png"},
  npc_dota_hero_keeper_of_the_light: { "image": "40.png"},
  npc_dota_hero_kunkka: { "image": "41.png"},
  npc_dota_hero_legion_commander: { "image": "42.png"},
  npc_dota_hero_leshrac: { "image": "43.png"},
  npc_dota_hero_lich: { "image": "44.png"},
  npc_dota_hero_life_stealer: { "image": "45.png"},
  npc_dota_hero_lina: { "image": "46.png"},
  npc_dota_hero_lion: { "image": "47.png"},
  npc_dota_hero_lone_druid: { "image": "48.png"},
  npc_dota_hero_luna: { "image": "49.png"},
  npc_dota_hero_lycan: { "image": "50.png"},
  npc_dota_hero_magnataur: { "image": "51.png"},
  npc_dota_hero_medusa: { "image": "52.png"},
  npc_dota_hero_meepo: { "image": "53.png"},
  npc_dota_hero_mirana: { "image": "54.png"},
  npc_dota_hero_monkey_king: { "image": "55.png"},
  npc_dota_hero_morphling: { "image": "56.png"},
  npc_dota_hero_naga_siren: { "image": "57.png"},
  npc_dota_hero_necrolyte: { "image": "58.png"},
  npc_dota_hero_nevermore: { "image": "59.png"},
  npc_dota_hero_night_stalker: { "image": "60.png"},
  npc_dota_hero_nyx_assassin: { "image": "61.png"},
  npc_dota_hero_obsidian_destroyer: { "image": "62.png"},
  npc_dota_hero_ogre_magi: { "image": "63.png"},
  npc_dota_hero_omniknight: { "image": "64.png"},
  npc_dota_hero_oracle: { "image": "65.png"},
  npc_dota_hero_phantom_assassin: { "image": "66.png"},
  npc_dota_hero_phantom_lancer: { "image": "67.png"},
  npc_dota_hero_phoenix: { "image": "68.png"},
  npc_dota_hero_puck: { "image": "69.png"},
  npc_dota_hero_pudge: { "image": "70.png"},
  npc_dota_hero_pugna: { "image": "71.png"},
  npc_dota_hero_queenofpain: { "image": "72.png"},
  npc_dota_hero_rattletrap: { "image": "73.png"},
  npc_dota_hero_razor: { "image": "74.png"},
  npc_dota_hero_riki: { "image": "75.png"},
  npc_dota_hero_rubick: { "image": "76.png"},
  npc_dota_hero_sand_king: { "image": "77.png"},
  npc_dota_hero_shadow_demon: { "image": "78.png"},
  npc_dota_hero_shadow_shaman: { "image": "79.png"},
  npc_dota_hero_shredder: { "image": "80.png"},
  npc_dota_hero_silencer: { "image": "81.png"},
  npc_dota_hero_skeleton_king: { "image": "82.png"},
  npc_dota_hero_skywrath_mage: { "image": "83.png"},
  npc_dota_hero_slardar: { "image": "84.png"},
  npc_dota_hero_slark: { "image": "85.png"},
  npc_dota_hero_sniper: { "image": "86.png"},
  npc_dota_hero_spectre: { "image": "87.png"},
  npc_dota_hero_spirit_breaker: { "image": "88.png"},
  npc_dota_hero_storm_spirit: { "image": "89.png"},
  npc_dota_hero_sven: { "image": "90.png"},
  npc_dota_hero_techies: { "image": "91.png"},
  npc_dota_hero_templar_assassin: { "image": "92.png"},
  npc_dota_hero_terrorblade: { "image": "93.png"},
  npc_dota_hero_tidehunter: { "image": "94.png"},
  npc_dota_hero_tinker: { "image": "95.png"},
  npc_dota_hero_tiny: { "image": "96.png"},
  npc_dota_hero_treant: { "image": "97.png"},
  npc_dota_hero_troll_warlord: { "image": "98.png"},
  npc_dota_hero_tusk: { "image": "99.png"},
  npc_dota_hero_undying: { "image": "100.png"},
  npc_dota_hero_ursa: { "image": "101.png"},
  npc_dota_hero_vengefulspirit: { "image": "102.png"},
  npc_dota_hero_venomancer: { "image": "103.png"},
  npc_dota_hero_viper: { "image": "104.png"},
  npc_dota_hero_visage: { "image": "105.png"},
  npc_dota_hero_warlock: { "image": "106.png"},
  npc_dota_hero_weaver: { "image": "107.png"},
  npc_dota_hero_windrunner: { "image": "108.png"},
  npc_dota_hero_wisp: { "image": "109.png"},
  npc_dota_hero_winter_wyvern: { "image": "110.png"},
  npc_dota_hero_witch_doctor: { "image": "111.png"},
  npc_dota_hero_zuus: { "image": "112.png"}
}

var i = 0;
var string = "{";
console.log(heroes.npc_dota_hero_zuus.image)
Object.keys(heroes).forEach(function(key) {
  string += key + ': { "image": "' + i + '.png"},\n';
  console.log(key + "\n\t" + i + ".png");
  i++;
});
string += "}";

var saveLocation = "C:\\Users\\Sam\\test.txt"
var fs = require('fs');
fs.writeFile(saveLocation, string, function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("The file was saved!");
});
